___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=np.array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
s=(5,5)
np.zeros(s)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
s=(4,4)
np.ones(s)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [ ]:
np.ones(s)*7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### 6. Create same array above with full method

In [ ]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(0,25,1).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,num=25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.16917311, 0.4908811 , 0.68461273, 0.02067306, 0.01539034])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.rand(25).reshape(5,5)

array([[0.65615118, 0.17503468, 0.88340402, 0.12248081, 0.023865  ],
       [0.42351951, 0.38755049, 0.31926212, 0.79367211, 0.43416191],
       [0.46893808, 0.41929532, 0.23950839, 0.79170603, 0.28005093],
       [0.33921374, 0.03079476, 0.30074844, 0.9695244 , 0.67384979],
       [0.88328125, 0.6621646 , 0.3814353 , 0.50011201, 0.7958738 ]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,51,size=12).reshape(3,4)

array([[33, 50, 49, 25],
       [44, 21, 47, 29],
       [21, 48, 25, 48]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.random.randint(0, 60, 48)

In [ ]:
ranarr.reshape(6,8)

array([[19,  9, 46, 35, 43, 25,  6, 11],
       [31, 21,  5, 59, 14, 15, 18, 39],
       [44, 34, 58, 28, 46, 25, 14, 21],
       [58, 46, 48,  4, 38, 57, 39, 48],
       [ 3, 42, 53,  3, 45, 47, 14, 40],
       [ 2,  5, 28, 14,  6,  3, 35, 27]])

In [ ]:
#reshape with -1
ranarr.reshape(-1)

array([19,  9, 46, 35, 43, 25,  6, 11, 31, 21,  5, 59, 14, 15, 18, 39, 44,
       34, 58, 28, 46, 25, 14, 21, 58, 46, 48,  4, 38, 57, 39, 48,  3, 42,
       53,  3, 45, 47, 14, 40,  2,  5, 28, 14,  6,  3, 35, 27])

In [ ]:
ranarr.itemsize

8

## Numpy Indexing and Selection


In [ ]:
#Create array below
my_array=np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16]])
my_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
my_array[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
my_array[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
my_array[1,0:3:2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
my_array[:,2:3]=77
my_array

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [ ]:
np.array([my_array[1,0],my_array[3,2]])

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
my_array[1:4:2,0:4:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
a1=np.array([1, 2, 4, 5, 6, 8, 9])
x1=a1[a1<10] 
y1=a1[a1>12]
print (('Sum of values smaller than 10: '),np.sum(x1))
print (('Sum of values bigger than 12: '),np.sum(y1))

Sum of values smaller than 10:  35
Sum of values bigger than 12:  0


In [ ]:
a2=np.array([77, 77, 77, 13, 14, 77, 16])
x2=a2[a2<10] 
y2=a2[a2>12]
print (('Sum of values smaller than 10: '),np.sum(x2))
print (('Sum of values bigger than 12: '),np.sum(y2))

Sum of values smaller than 10:  0
Sum of values bigger than 12:  351


In [ ]:
a3=np.array([78, 79, 81, 18, 20, 85, 25])
x3=a3[a3<10] 
y3=a3[a3>12]
print (('Sum of values smaller than 10: '),np.sum(x3))
print (('Sum of values bigger than 12: '),np.sum(y3))

Sum of values smaller than 10:  0
Sum of values bigger than 12:  386


#### 21. Get the standard deviation of the result above

In [ ]:
std1=np.array([78, 79, 81, 18, 20, 85, 25])
np.std(std1)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
k1=np.array([[ 1,  2, 3,  4],       [ 5,  6, 4,  8],     [ 9, 10, 5, 12],       [13, 14, 6, 16]])
k1

array([[ 1,  2,  3,  4],
       [ 5,  6,  4,  8],
       [ 9, 10,  5, 12],
       [13, 14,  6, 16]])

In [ ]:
np.sum(k1[:,1])

32

#### 23. Get the median,mean and std of 3rd column from array above

In [ ]:
#median
np.median(k1[:,2])


4.5

In [ ]:
#mean
np.mean(k1[:,2])

4.5

In [ ]:
#std
np.std(k1[:,2])

1.118033988749895

# Pandas Section

In [3]:
import pandas as pd
from google.colab import files
data=files.upload()

Saving Salaries.csv to Salaries.csv


**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [4]:
Slr=pd.read_csv('Salaries.csv')

In [123]:
Slr.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [12]:
Slr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [13]:
Slr.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [82]:
Slr.groupby('Year').size().sort_values(ascending=False)

Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

**Print out max and avg Totalpay**

In [27]:
#max
Slr['TotalPay'].max()

567595.43

In [84]:
#avg
Slr['TotalPay'].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [121]:
AvgTotalPay=Slr['TotalPay'].mean()
A=Slr[Slr['TotalPay']>AvgTotalPay]
len(A)

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [38]:
Slr[Slr['EmployeeName']=="ALBERT PARDINI"]['TotalPayBenefits']


2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [144]:
Slr['TotalPayBenefits'].min()

-618.13

**What are the unique Jobs in dataset?**

In [54]:
Slr['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [65]:
print(Slr.groupby('JobTitle').size().nsmallest(3))

JobTitle
ACPO,JuvP, Juv Prob (SFERS)           1
ACUPUNCTURIST                         1
ADMINISTRATOR, SFGH MEDICAL CENTER    1
dtype: int64


**How many people earned more than avg in 2012**

In [212]:
AvgTotalPay=Slr['TotalPay'].mean()
len(Slr[(Slr['TotalPay']>AvgTotalPay)&(Slr['Year']==2012)])


16716

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [252]:
sal_new=Slr.iloc[:,[True,True,True,False,False,False,False,True,True,False,False,False,False]]
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [253]:
sal_new=sal_new.loc[:,[False,True,True,True,True]]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [263]:
min_salary=sal_new['TotalPay'].min()
min_salary
avg_salary=sal_new['TotalPay'].mean()
avg_salary
sal_new[(sal_new['TotalPay']<avg_salary) & (sal_new['TotalPay']>min_salary)]['EmployeeName']

15847     TATYANA ROTENBERG
15848           WINSTON HOM
15849          CRAIG RIGLER
15850             WENDY TAN
15851        KENNETH BREWER
                ...        
148648          Leon Walker
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
Name: EmployeeName, Length: 79164, dtype: object